### ISSUE TITLE
BLS Tool: Build for Windows (x64 & arm64)

### ISSUE THREAD

**Issue by wmerfalen** [dashhive/bls#4]

**Comment by coolaj86** [comment]
Sounds like x86_64 is working and we can put arm64 on hold, closing as complete (and improvements put in #8).

**Comment by jojobyte** [comment]
Tested for QA on Windows
![image](https://user-images.githubusercontent.com/184880/194676220-6d573668-b1a2-4411-af44-6cb21629fec6.png)
